### PR TITLE
Alternative Idea for Code Generation

### PR DESCRIPTION
**Pull request by avbk**
Hey Florin,

in the last couple of weeks I was thinking of an approach to ease the use of the library. I had the idea to not create static keys, but to create classes with getters and methods, so that one can easily use parametrized strings and/or plurals. 

And without further ado some examples, so you don't need to read through the complete pull request to get a first understanding of my idea :slightly_smiling_face: 

Let's say, we have this `en.json`:
```json
{
  "language": {
    "name": {
      "en": "English",
      "es": "Spanish",
      "fa": "Persian"
    },
    "selected_message": "Currently selected language is {language}",
  },
  "plural": {
    "banana": {
      "1": "banana",
      "else": "bananas"
    },
    "demo_with_args": {
      "0": "I have no {things}.",
      "1": "I have one {things}.",
      "else": "I have {{value}} {things}."
    }
  }
}
```

As usual you would need to create the following `keys.dart`, with small changes to your version:
```dart
import 'package:flutter/foundation.dart';
import 'package:flutter_translate/flutter_translate.dart';
import 'package:flutter_translate_annotations/flutter_translate_annotations.dart';

part 'keys.g.dart';

@TranslateKeysOptions(path: 'assets/i18n')
class _$Keys {}

const i18n = const _$_$Keys();
```

After running the build_runner you can use it like this:
```dart
print(i18n.language.selectedMessage(language: i18n.language.name.es)); 
 
final banana = i18n.plural.banana;
final demoWithArgs = i18n.plural.demoWithArgs;
[0,1,42].forEach((x) =>print(demoWithArgs(x, things: banana(x))));
```

which results in:
```
Currently selected language is Spanish
I have no bananas.
I have one banana.
I have 42 bananas.
```

I've implemented a rough solution today and I think it needs a bit of final polishing and of course the docs need to be updated as well. Also it totally breaks the existing generator :see_no_evil: 
Thus I think it at least should be released as new major version (so 2.0.0 I guess?). Or maybe it should even be moved it into a separate project, because it otherwise would force existing users to do some heavy migration? What do you think?

Best regards
Alex

### CODE REVIEW

**Comment by avbk** [comment]
Hey Florin,

I found some time to continue the work on this PR. I was able to simplify the base file a bit:
```dart
import 'package:flutter/foundation.dart';
import 'package:flutter_translate/flutter_translate.dart';
import 'package:flutter_translate_gen/flutter_translate_gen.dart';

part 'i18n.g.dart';

@FlutterTranslate(
  path: 'assets/i18n.v2',
)
const i18n = _$I18n();
```
I have also added a validator (inspired by #1) to check if keys or arguments are missing. The missing keys will cause a build_runner error, but it can be configured to only print a warning: 
```
[INFO] Running build...
[INFO] 1.1s elapsed, 0/2 actions completed.
[INFO] 4.8s elapsed, 1/2 actions completed.
[INFO] 10.8s elapsed, 1/2 actions completed.
[WARNING] flutter_translate_gen:static_keys_generator on lib/localization/i18n.dart:
Flutter Translate-------------------------------------------------------

Missing translation "es:simple"
Missing translation "es:params"
Missing translation "es:nested.child"
Missing translation "es:nested.nested.child"
Missing translation "es:plural.banana.1"
Missing translation "es:plural.banana.else"
Missing translation "es:plural.demo_with_args.0"
Missing translation "es:plural.demo_with_args.1"
Missing translation "es:plural.demo_with_args.else"
------------------------------------------------------------------------

[INFO] Running build completed, took 11.0s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 39ms

[INFO] Succeeded after 11.1s with 2 outputs (5 actions)
```

The generated file will now contain the translated text as dart-docs, so that the IDE can show the translation when opening the autocomplete window. The generated class looks like this now:
```
class _$AppBar {
  const _$AppBar();

  /// Translations:
  /// * en: Welcome to the home page
  /// * es: Bienvenido a la página de inicio
  ///
  /// parsed from: app_bar.title
  String get title => translate('app_bar.title');
}
``` 

And finally this pull request also contains a fix for #3 by only including files ending with `.json`

I'm curious about your thoughts :slightly_smiling_face: 
Alex

**Comment by avbk** [comment]
Hey @bratan, I've just continued working on the PR and I've added some options to make it backwards compatible. 

Now if you write
```dart
@FlutterTranslate(
  path: 'assets/i18n',
  keysStyle: KeysStyle.keysOnly,
  nestingStyle: NestingStyle.flat,
  caseStyle: CaseStyle.titleCase,
)
const Keys = _$Keys();
```
The generator will create a file, which should be fully compatible to the old style. And while doing so I've also added the camelCase option, as it was asked for in #4 

Still looking forward for your feedback :slightly_smiling_face:

**Comment by bratan** [comment]
Hey @avbk, sorry for the slow reply. I`m quite busy these days and don't have time to test or implement new features, except bug fixes if necessary. You could release these features as a separate library/package.

**Comment by avbk** [comment]
Hey @bratan, thanks for your reply and I am sorry to hear that you are so busy nowadays :slightly_frowning_face: 

Since the new generator is fully backwards compatible (except for a slightly different style of using the annotations) and because it targets all of the currently opened issues I would rather contribute to the upstream of your project than to create a new generator library. And actually I've written a small amount of tests and I'm already using this generator in two larger projects -- one with the new style and one with the old style -- without facing any issues yet. So I'm confident that it will work fine... All it needs to be ready are some updated docs  :wink:

If you are under stress, then maybe you need a helping hand? I could support you maintaining this project, if that helps? If not, I most likely would close this PR and create a new generator project... Just let me know what you think.

Best regards,
Alex

**Comment by bratan** [comment]
Hey @avbk, I think is better you create a separate generator project if you wish.

**Pull request closed without merging**
